### YamlMime:ManagedReference
items:
- uid: SudokuSpice.ConstraintBased.PossibleValueState
  commentId: T:SudokuSpice.ConstraintBased.PossibleValueState
  id: PossibleValueState
  parent: SudokuSpice.ConstraintBased
  children:
  - SudokuSpice.ConstraintBased.PossibleValueState.DROPPED
  - SudokuSpice.ConstraintBased.PossibleValueState.SELECTED
  - SudokuSpice.ConstraintBased.PossibleValueState.UNKNOWN
  langs:
  - csharp
  - vb
  name: PossibleValueState
  nameWithType: PossibleValueState
  fullName: SudokuSpice.ConstraintBased.PossibleValueState
  type: Enum
  source:
    remote:
      path: SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
      branch: internal-puzzle
      repo: https://github.com/MorganR/SudokuSpice.git
    id: PossibleValueState
    path: ../SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
    startLine: 5
  assemblies:
  - SudokuSpice
  namespace: SudokuSpice.ConstraintBased
  summary: "\nIndicates if a <xref href=\"SudokuSpice.ConstraintBased.PossibleSquareValue\" data-throw-if-not-resolved=\"false\"></xref> is still possible, selected, or dropped.\n"
  example: []
  syntax:
    content: 'public enum PossibleValueState : int'
    content.vb: Public Enum PossibleValueState As Integer
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: SudokuSpice.ConstraintBased.PossibleValueState.UNKNOWN
  commentId: F:SudokuSpice.ConstraintBased.PossibleValueState.UNKNOWN
  id: UNKNOWN
  parent: SudokuSpice.ConstraintBased.PossibleValueState
  langs:
  - csharp
  - vb
  name: UNKNOWN
  nameWithType: PossibleValueState.UNKNOWN
  fullName: SudokuSpice.ConstraintBased.PossibleValueState.UNKNOWN
  type: Field
  source:
    remote:
      path: SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
      branch: internal-puzzle
      repo: https://github.com/MorganR/SudokuSpice.git
    id: UNKNOWN
    path: ../SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
    startLine: 10
  assemblies:
  - SudokuSpice
  namespace: SudokuSpice.ConstraintBased
  summary: "\nThis <xref href=\"SudokuSpice.ConstraintBased.PossibleSquareValue\" data-throw-if-not-resolved=\"false\"></xref> is still possible.\n"
  example: []
  syntax:
    content: UNKNOWN = 0
    return:
      type: SudokuSpice.ConstraintBased.PossibleValueState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SudokuSpice.ConstraintBased.PossibleValueState.SELECTED
  commentId: F:SudokuSpice.ConstraintBased.PossibleValueState.SELECTED
  id: SELECTED
  parent: SudokuSpice.ConstraintBased.PossibleValueState
  langs:
  - csharp
  - vb
  name: SELECTED
  nameWithType: PossibleValueState.SELECTED
  fullName: SudokuSpice.ConstraintBased.PossibleValueState.SELECTED
  type: Field
  source:
    remote:
      path: SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
      branch: internal-puzzle
      repo: https://github.com/MorganR/SudokuSpice.git
    id: SELECTED
    path: ../SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
    startLine: 14
  assemblies:
  - SudokuSpice
  namespace: SudokuSpice.ConstraintBased
  summary: "\nThis <xref href=\"SudokuSpice.ConstraintBased.PossibleSquareValue\" data-throw-if-not-resolved=\"false\"></xref> has been selected.\n"
  example: []
  syntax:
    content: SELECTED = 1
    return:
      type: SudokuSpice.ConstraintBased.PossibleValueState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SudokuSpice.ConstraintBased.PossibleValueState.DROPPED
  commentId: F:SudokuSpice.ConstraintBased.PossibleValueState.DROPPED
  id: DROPPED
  parent: SudokuSpice.ConstraintBased.PossibleValueState
  langs:
  - csharp
  - vb
  name: DROPPED
  nameWithType: PossibleValueState.DROPPED
  fullName: SudokuSpice.ConstraintBased.PossibleValueState.DROPPED
  type: Field
  source:
    remote:
      path: SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
      branch: internal-puzzle
      repo: https://github.com/MorganR/SudokuSpice.git
    id: DROPPED
    path: ../SudokuSpice/ConstraintBased/framework/PossibleValueState.cs
    startLine: 19
  assemblies:
  - SudokuSpice
  namespace: SudokuSpice.ConstraintBased
  summary: "\nThis <xref href=\"SudokuSpice.ConstraintBased.PossibleSquareValue\" data-throw-if-not-resolved=\"false\"></xref> has been dropped, i.e. it is no longer possible\nwith the currently selected values.\n"
  example: []
  syntax:
    content: DROPPED = 2
    return:
      type: SudokuSpice.ConstraintBased.PossibleValueState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SudokuSpice.ConstraintBased.PossibleSquareValue
  commentId: T:SudokuSpice.ConstraintBased.PossibleSquareValue
  parent: SudokuSpice.ConstraintBased
  name: PossibleSquareValue
  nameWithType: PossibleSquareValue
  fullName: SudokuSpice.ConstraintBased.PossibleSquareValue
- uid: SudokuSpice.ConstraintBased
  commentId: N:SudokuSpice.ConstraintBased
  name: SudokuSpice.ConstraintBased
  nameWithType: SudokuSpice.ConstraintBased
  fullName: SudokuSpice.ConstraintBased
- uid: SudokuSpice.ConstraintBased.PossibleValueState
  commentId: T:SudokuSpice.ConstraintBased.PossibleValueState
  parent: SudokuSpice.ConstraintBased
  name: PossibleValueState
  nameWithType: PossibleValueState
  fullName: SudokuSpice.ConstraintBased.PossibleValueState
