name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build SudokuSpice/SudokuSpice.csproj --configuration Release --no-restore
    - name: Test Public
      run: dotnet test SudokuSpice.Test --configuration Release --verbosity normal --no-restore
    - name: Test Internal
      run: dotnet test SudokuSpice.InternalTest --configuration Debug --verbosity normal --no-restore
