name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test Public
      run: dotnet test SudokuSpice.Test --configuration Release --no-build --verbosity normal
    - name: Test Internal
      run: dotnet test SudokuSpice.InternalTest --configuration Debug --no-restore --verbosity normal
