name: Update docs

on:
  push:
    branches: [ master ]
    tags-ignore: automated-docs

jobs:
  update-docs:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore SudokuSpiceDocs/SudokuSpiceDocs.csproj 
    - name: Build
      run: dotnet build SudokuSpiceDocs/SudokuSpiceDocs.csproj --no-restore
    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Automated docs update" 
        git tag "automated-docs"
        git push --tags
